#!/usr/bin/env python


"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
"""

MAX = 4000000

computed = []

def fib():
    a, b = 0, 1
    while 1:
        yield a
        a, b = b, a + b

gen = fib()
while True:
    i = gen.next()
    
    if i > MAX:
        break;

    if i % 2 is 0:
        computed.append( i )

print sum(computed)
